#!/bin/sh
#
# Start the rpi-pwrbtn client...
#

case "$1" in
  start)
	echo "Starting power button client..."
	rpi-pwrbtn_client.sh &
	;;
  stop)
	echo -n "Stopping power button client..."
	killall rpi-pwrbtn_client.sh
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

